### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rinahong** [kluein/trayclient#2]
There are total of 15 TRAY.IO embedded APIs(GRAPHQL). I don't think we need all of them but here is a list of APIs to track what has been implemented.

- [ ] Users/Queries/Get Users
- [ ] Users/Mutations/Create New user
- [ ] Users/Mutations/Create User Token
- [ ] Users/Mutations/Create Config Wizard Authorization
- [ ] Users/Mutations/Delete User

- [ ] Authentications/Queries/Get User Authentications
- [ ] Authentications/Mutations/Create User Auth
- [ ] Authentications/Mutations/Delete User Auth

- [ ] Solutions/Get Solutions

- [ ] Solutions Instances/Queries/Get Solution Instances
- [ ] Solutions Instances/Mutations/Create Solution Instance
- [ ] Solutions Instances/Mutations/Update Solution Instance
- [ ] Solutions Instances/Mutations/Upgrade Solution Instance
- [ ] Solutions Instances/Mutations/Delete Solution Instance

- [ ] Call Connector

**Comment by rinahong** [comment]
Note: 
- Users/Mutations/Create New user is added in `trayclient/authentications.rb`
- Users/Mutations/Create User Token is added in `trayclient/authentications.rb`
